hostName = "192.0.1.2"
port = 9090
enableRemote = false
maxPayload = 0.321

# The below TOML table specification must be provided for module execution
# [organizationName.packageName.submoduleName]
# variable-name = value
