name: ballerina-distribution

on:
  push:
    branches:
      - master
      - ballerina-1.1.x #TODO: Change to ballerina-1.2?
      - feature/gradle-migration #TODO: Remove after testing
  pull_request:
    branches:
      - master
      - stage
      - ballerina-1.1.x #TODO: Change to ballerina-1.2?

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Ballerina Distribution
        env:
          packagePAT: ${{ secrets.READ_PACKAGE_PAT }}
          packageUser: ${{ secrets.PUBLISH_USER }}
        run: ./gradlew build
