name: Ballerina Distribution Build

on:
  push:
    branches:
      - master
      - ballerina-1.1.x
  pull_request:
    branches:
      - master
      - ballerina-1.1.x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: Build Ballerina Distribution
      with:
        repo-token: ${{ secrets.PUBLISH_PAT }}
      run: mvn clean install -B -V
