name: Ballerina Distribution Build

on:
  push:
    branches:
      - master
      - feature/gradle-migration
  pull_request:
    branches:
      - master
      - ballerina-1.1.x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Ballerina Distribution
        env:
          packagePAT: ${{ secrets.READ_PACKAGE_PAT }}
          packageUser: ${{ secrets.PUBLISH_USER }}
        run: ./gradlew build