name: Ballerina Distribution Build

on:
  push:
    branches:
      - master
      - ballerina-1.1.x
  pull_request:
    branches:
      - master
      - ballerina-1.1.x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v4
      with:
        repositories: '[{ "id": "github", "url": "https://maven.pkg.github.com/ballerina-platform/ballerina-update-tool" }]'
        servers: '[{ "id": "github", "username": "${{ secrets.PUBLISH_USER }}" , "password": "${{ secrets.PUBLISH_PAT }}" }]'
    - name: Set credentials
      run: echo "Set enviroments"
      env:
        packagePAT: ${{ secrets.READ_PACKAGE_PAT }}
        packageUser: ${{ secrets.PUBLISH_USER }}
    - name: Build Ballerina Distribution
      run: mvn -s settings.xml clean install -B -V
