name: Ballerina Distribution Build

on:
  push:
    branches:
      - master
      - ballerina-1.1.x
  pull_request:
    branches:
      - master
      - ballerina-1.1.x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: Set credentials
      run: echo "Set enviroments"
      env:
        packagePAT: ${{ secrets.READ_PACKAGE_PAT }}
        packageUser: ${{ secrets.PUBLISH_USER }}
    - name: Build Ballerina Distribution
      env:
        GITHUB_TOKEN: ${{ secrets.READ_PACKAGE_PAT }}
      run: mvn -s settings.xml clean install -B -V
